// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3rost_dYEsz8U6p6e44yMOzb-y_S4rKM',
    appId: '1:1079895964617:web:7dc7f0679409f575e34618',
    messagingSenderId: '1079895964617',
    projectId: 'social-app-7645e',
    authDomain: 'social-app-7645e.firebaseapp.com',
    storageBucket: 'social-app-7645e.appspot.com',
    measurementId: 'G-GW4F117WWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtKQLAtj85K8Jmub2t0ISRjW7irhX3GD4',
    appId: '1:1079895964617:android:4045a2e1b40a1692e34618',
    messagingSenderId: '1079895964617',
    projectId: 'social-app-7645e',
    storageBucket: 'social-app-7645e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTCOzh2IR8Zx2uWlRMpd68fV4xekRGuO4',
    appId: '1:1079895964617:ios:b263bd15a878dcf9e34618',
    messagingSenderId: '1079895964617',
    projectId: 'social-app-7645e',
    storageBucket: 'social-app-7645e.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTCOzh2IR8Zx2uWlRMpd68fV4xekRGuO4',
    appId: '1:1079895964617:ios:b263bd15a878dcf9e34618',
    messagingSenderId: '1079895964617',
    projectId: 'social-app-7645e',
    storageBucket: 'social-app-7645e.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3rost_dYEsz8U6p6e44yMOzb-y_S4rKM',
    appId: '1:1079895964617:web:302e9649783cc3cfe34618',
    messagingSenderId: '1079895964617',
    projectId: 'social-app-7645e',
    authDomain: 'social-app-7645e.firebaseapp.com',
    storageBucket: 'social-app-7645e.appspot.com',
    measurementId: 'G-7Y4JY4G02D',
  );
}
